title: Awesome Amber Title
author: Amber vick
email: amber.vick@arcadis-us.com
description: > # this means to ignore newlines until "baseurl:"
This blog is all about how awesome Amber is!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
